### PR TITLE
Retrieve all oos objects

### LINKED ISSUE #82: Wrong amount on OOS cost
The OOS cost calculation is based on a sum of objects size per bucket.
The problem is `client.list_objects_v2()` on line 3 of the following code (oapi/oos.rs) return only the first 1000 objects : 

```rust 
    async fn list_objects(&mut self, bucket_name: &str) -> Option<Vec<Object>> {
        let client = Client::new(&self.aws_config);
        let req = client.list_objects_v2().prefix("").bucket(bucket_name);

        // TODO: handle throttling
        let Ok(result) = req.send().await else {
            warn!("warning: error while retrieving the object of {bucket_name}");
            return None;
        };

        let objects = result.contents().unwrap_or_default();
        let objects = objects.to_vec();
        Some(objects)
    }
```

In the AWS SDK Documentation : 

```
By default the action returns up to 1,000 key names. The response might contain fewer keys but will never contain more. 
```

It is possible to update this maximum number with the `max_keys` parameter but there is a risk that the operation will take a long time on buckets with many objects (millions or more).

### PR DESCRIPTION
**Pull request by outscale-mdr**
Previously only the 1000 first objects was retrieved, now we use the paginator to retrieve all the objects. 

Closes #82

### CODE REVIEW

File: src/oapi/oos.rs [hunk 1]
```diff
@@ -10,6 +12,8 @@ use crate::{
 
 use super::Input;
 
+const FETCH_WAIT: u64 = 5;
```
Comment (jerome-jutteau) [inline src/oapi/oos.rs:15]: explicit name variable could include unit (like seconds): FETCH_WAIT_S

**Review by jerome-jutteau — APPROVED** [review]
